language: "zh"
project: "ivr_nlu"
fixed_model_name: "nlu"
path: "models"
pipeline:
  - name: "starbot.ThulacTokenizer"
  - name: "nlp_mitie"
    model: "total_word_feature_extractor.dat"
  - name: "ner_mitie"
  - name: "ner_synonyms"
  - name: "intent_entity_featurizer_regex"
  - name: "intent_featurizer_mitie"
  - name: "intent_classifier_sklearn"
