policies:
  - name: starbot.policy.directaction.DirectAction
    priority: 4
#  - name: FallbackPolicy
#    fallback_action_name: 'action_default_fallback'
#    priority: 3
  - name: FormPolicy
    priority: 6
